### ISSUE TITLE
Checklist for submission

### ISSUE THREAD

**Issue by eread-usgs** [USGS-R/geolakes#16]
- [x] Title page with title, authors, affiliations, complete addresses, and three key points
- [x] Text requirements met (http://publications.agu.org/author-resource-center/text-requirements/)
- [x] Descriptive headings for key sections
- [x] An abstract that is <250 words
- [x] Continuous line numbers throughout text
- [x] Figures and tables go together with their captions and can be placed near where cited in text.
- [x] Complete references
- [x] An acknowledgement section that includes where readers can access or find supporting data
- [x] An acknowledgement section that includes all funding info from each author pertaining to this work
- [x] An acknowledgement section that includes any conflicts of interest for any author that are not apparent from their affiliations or funding
- [x] Suggestions of up to five reviewers
- [x] ORCID for each author
- [x] Cover letter explaining your submission to the editors and identifying any conflicts of interest. 
- [x] Supporting information main file (http://publications.agu.org/author-resource-center/auxiliary-materials-guidelines/) 
- [x] Supporting information zipped code file, named according to GEMS (see bottom of this page: http://publications.agu.org/author-resource-center/auxiliary-materials-guidelines/ )
